---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: intsall apache2 package
    apt:
      name: apache2
      state: latest

  - name: add php supprt for apache
    apt:
      name: libapache2-mod-php
      state: latest
